name: checkout
on: [push]

jobs:
    descargar-el-repositorio:
        runs-on: ubuntu-latest
        steps:
            - name: List Files befor
              run: ls -a
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN  }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List Files After
              run: ls -a 
