name: Docker Workflow
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: node:20.3-alpine3.17
        #credentials:
        #    username: ${{ secrets.DOCKER_USERNAME }}
        #    password: ${{ secrets.DOCKER_PASSWORD }}
        #   env:
        #     API_URL: some_url.com
            ports:
              - 80
        steps:
            - name: log node $ os versions
              run: |
                node -v
                cat /etc/os-release
            - name: log env
              run: echo $API_URL
            - name: docker in steps
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: /usr/bin/node
                args: -p 2+3
