name: Learning Variables
on : [push]

jobs:
  Primervariable:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: printing my variable
        run: |
          echo "My variable by default ${{ vars.VARIABLE1 }}"
          echo "Done"