# .github/workflows/pagerduty-alert.yaml
name: PagerDuty Alert Handler

on:
  repository_dispatch:
    types: [pagey.ping]

jobs:
  handle-pagerduty-alert:
    runs-on: ubuntu-latest
    steps:
    - name: Debug PagerDuty Payload
      run: |
        echo "Payload completo de PagerDuty:"
        echo '${{ toJson(github.event) }}' | jq '.'
        
    - name: Procesar Incidente
      run: |
        # PagerDuty envía los datos en client_payload
        echo "Procesando incidente de PagerDuty..."
        # Aquí va tu lógica de automatización
