name: status Check por mi mismo
on: [push]
run-name: "Status Check by ${{ github.actor }}, event: ${{ github.event_name }}" #me va a mostrar quien lo lanzo y que evento fue el que lo disparo

jobs:
    Job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              run: sleep 20
            - name: step 2
              id: step2
              run: exit 1
            - name: step 3
              if: cancelled()
              run: echo 'run on cancelled'

    Job-2:
        runs-on: ubuntu-latest
        needs: Job-1 #necesito que el job 1 termine para que este job se ejecute
        steps:
            - name: Job 2
              if: failure() #si el job 1 falla, este job se ejecuta
              run: echo "Hello from Job 2"
